# Generated by Django 5.2.1 on 2025-05-18 04:13

import django.core.validators
import django.db.models.deletion
import principal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('duracion', models.FloatField(help_text='Duración en horas')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nivel', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('PAYPAL', 'PayPal')], max_length=13)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.IntegerField(unique=True)),
                ('dv', models.CharField(max_length=1)),
                ('correo', models.EmailField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'indexes': [models.Index(fields=['rut'], name='idx_rut')],
            },
        ),
        migrations.CreateModel(
            name='HoraClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.clase')),
            ],
            options={
                'verbose_name': 'Horario de Clase',
                'verbose_name_plural': 'Horarios de Clases',
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.materia'),
        ),
        migrations.AddField(
            model_name='clase',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.nivel'),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('rut', models.IntegerField(unique=True)),
                ('dv', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('titulo', models.FileField(blank=True, null=True, upload_to=principal.models.profesor_titulo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), principal.models.validate_pdf], verbose_name='Título PDF')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'indexes': [models.Index(fields=['rut'], name='idx_profesor_rut')],
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.profesor'),
        ),
        migrations.CreateModel(
            name='ProfesorMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.profesor')),
            ],
            options={
                'verbose_name': 'Profesor-Materia',
                'verbose_name_plural': 'Profesores-Materias',
            },
        ),
        migrations.CreateModel(
            name='ReservaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.alumno')),
                ('hora_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.horaclase')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.pago')),
            ],
            options={
                'verbose_name': 'Reserva de Clase',
                'verbose_name_plural': 'Reservas de Clases',
            },
        ),
        migrations.AddIndex(
            model_name='horaclase',
            index=models.Index(fields=['fecha', 'inicio'], name='idx_fecha_inicio'),
        ),
        migrations.AddIndex(
            model_name='clase',
            index=models.Index(fields=['profesor'], name='idx_clase_profesor'),
        ),
        migrations.AlterUniqueTogether(
            name='profesormateria',
            unique_together={('profesor', 'materia')},
        ),
        migrations.AddIndex(
            model_name='reservaclase',
            index=models.Index(fields=['alumno'], name='idx_reserva_alumno'),
        ),
        migrations.AlterUniqueTogether(
            name='reservaclase',
            unique_together={('hora_clase', 'alumno')},
        ),
    ]
