# Generated by Django 5.2.1 on 2025-05-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='password',
            field=models.CharField(default=1234, max_length=128, verbose_name='Contraseña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='password',
            field=models.CharField(default=1234, max_length=128, verbose_name='Contraseña'),
            preserve_default=False,
        ),
    ]
