# Generated by Django 5.2.1 on 2025-06-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='profesormateria',
            table='profesor_materia',
        ),
    ]
