# Generated by Django 5.2.1 on 2025-07-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alumno_descripcion_profesor_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_alumnos/'),
        ),
    ]
