# Generated by Django 5.2.1 on 2025-05-29 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alumno_password_profesor_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='materiales/')),
                ('link', models.URLField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.reservaclase')),
            ],
        ),
    ]
