# Generated by Django 5.2.1 on 2025-07-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alumno_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_profesores/'),
        ),
    ]
