# Generated by Django 5.2.1 on 2025-05-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_materialclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaclase',
            name='mensaje_alumno',
            field=models.TextField(blank=True, null=True),
        ),
    ]
