# Generated by Django 5.2.1 on 2025-07-02 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_profesor_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobroProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='principal.profesor')),
            ],
            options={
                'verbose_name': 'Cobro de Profesor',
                'verbose_name_plural': 'Cobros de Profesores',
                'db_table': 'cobro_profesor',
            },
        ),
    ]
