# Generated by Django 5.2.1 on 2025-06-04 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_reservaclase_mensaje_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialclase',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='principal.reservaclase'),
        ),
    ]
