# Generated by Django 5.2.1 on 2025-06-04 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_materialclase_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='principal.reservaclase')),
            ],
        ),
    ]
